"""Update delivery assignments for unified orders

Revision ID: 0ced161c4100
Revises: b7dceb64d029
Create Date: 2026-06-21 12:42:53.487975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ced161c4100'
down_revision = 'b7dceb64d029'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_assignments', sa.Column('subscription_delivery_id', sa.UUID(), nullable=True))
    op.add_column('delivery_assignments', sa.Column('fruit_order_id', sa.UUID(), nullable=True))
    op.add_column('delivery_assignments', sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_delivery_assignments_delivery_id', table_name='delivery_assignments')
    op.create_index(op.f('ix_delivery_assignments_fruit_order_id'), 'delivery_assignments', ['fruit_order_id'], unique=False)
    op.create_index(op.f('ix_delivery_assignments_subscription_delivery_id'), 'delivery_assignments', ['subscription_delivery_id'], unique=False)
    op.drop_constraint('delivery_assignments_delivery_id_fkey', 'delivery_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_assignments', 'fruit_orders', ['fruit_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'delivery_assignments', 'subscription_deliveries', ['subscription_delivery_id'], ['id'], ondelete='CASCADE')
    op.drop_column('delivery_assignments', 'accepted_at')
    op.drop_column('delivery_assignments', 'delivery_id')
    op.create_check_constraint(
        'ck_delivery_assignments_single_order',
        'delivery_assignments',
        "(subscription_delivery_id IS NOT NULL AND fruit_order_id IS NULL) OR (subscription_delivery_id IS NULL AND fruit_order_id IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_assignments', sa.Column('delivery_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('delivery_assignments', sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'delivery_assignments', type_='foreignkey')
    op.drop_constraint(None, 'delivery_assignments', type_='foreignkey')
    op.create_foreign_key('delivery_assignments_delivery_id_fkey', 'delivery_assignments', 'subscription_deliveries', ['delivery_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_delivery_assignments_subscription_delivery_id'), table_name='delivery_assignments')
    op.drop_index(op.f('ix_delivery_assignments_fruit_order_id'), table_name='delivery_assignments')
    op.create_index('ix_delivery_assignments_delivery_id', 'delivery_assignments', ['delivery_id'], unique=True)
    op.drop_column('delivery_assignments', 'picked_up_at')
    op.drop_column('delivery_assignments', 'fruit_order_id')
    op.drop_column('delivery_assignments', 'subscription_delivery_id')
    op.drop_constraint('ck_delivery_assignments_single_order', 'delivery_assignments', type_='check')
    # ### end Alembic commands ###
