"""add_fruit_ordering_workflow_fields

Revision ID: 377898d26092
Revises: 5036e31014de
Create Date: 2026-06-30 11:07:40.479109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377898d26092'
down_revision = '5036e31014de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_slots',
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_slots_id'), 'delivery_slots', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_slots_slot_date'), 'delivery_slots', ['slot_date'], unique=False)
    op.add_column('addresses', sa.Column('recipient_name', sa.String(length=200), nullable=True))
    op.add_column('addresses', sa.Column('recipient_phone', sa.String(length=20), nullable=True))
    op.add_column('fruit_orders', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('fruit_orders', sa.Column('delivery_slot', sa.String(length=100), nullable=True))
    op.add_column('fruit_orders', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('fruit_orders', sa.Column('review_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fruit_orders', 'review_text')
    op.drop_column('fruit_orders', 'rating')
    op.drop_column('fruit_orders', 'delivery_slot')
    op.drop_column('fruit_orders', 'delivery_date')
    op.drop_column('addresses', 'recipient_phone')
    op.drop_column('addresses', 'recipient_name')
    op.drop_index(op.f('ix_delivery_slots_slot_date'), table_name='delivery_slots')
    op.drop_index(op.f('ix_delivery_slots_id'), table_name='delivery_slots')
    op.drop_table('delivery_slots')
    # ### end Alembic commands ###
