"""add_inapp_notification_fields

Revision ID: 3b195ec730cf
Revises: 61209e92294b
Create Date: 2026-06-17 05:44:44.412858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b195ec730cf'
down_revision = '61209e92294b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('action_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('reference_id', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_column('notifications', 'is_deleted')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'reference_id')
    op.drop_column('notifications', 'action_type')
    op.drop_column('notifications', 'category')
    # ### end Alembic commands ###
