"""add_assignment_history

Revision ID: 54565e780e3d
Revises: 6dec8b9db0d8
Create Date: 2026-06-20 06:49:32.063182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54565e780e3d'
down_revision = '6dec8b9db0d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_assignment_history',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('previous_partner_id', sa.UUID(), nullable=True),
    sa.Column('new_partner_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_id'], ['subscription_deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_partner_id'], ['delivery_partners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_partner_id'], ['delivery_partners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_assignment_history_changed_by_id'), 'delivery_assignment_history', ['changed_by_id'], unique=False)
    op.create_index(op.f('ix_delivery_assignment_history_delivery_id'), 'delivery_assignment_history', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_assignment_history_id'), 'delivery_assignment_history', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_assignment_history_new_partner_id'), 'delivery_assignment_history', ['new_partner_id'], unique=False)
    op.create_index(op.f('ix_delivery_assignment_history_previous_partner_id'), 'delivery_assignment_history', ['previous_partner_id'], unique=False)
    op.add_column('delivery_assignments', sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_assignments', 'picked_up_at')
    op.drop_index(op.f('ix_delivery_assignment_history_previous_partner_id'), table_name='delivery_assignment_history')
    op.drop_index(op.f('ix_delivery_assignment_history_new_partner_id'), table_name='delivery_assignment_history')
    op.drop_index(op.f('ix_delivery_assignment_history_id'), table_name='delivery_assignment_history')
    op.drop_index(op.f('ix_delivery_assignment_history_delivery_id'), table_name='delivery_assignment_history')
    op.drop_index(op.f('ix_delivery_assignment_history_changed_by_id'), table_name='delivery_assignment_history')
    op.drop_table('delivery_assignment_history')
    # ### end Alembic commands ###
