"""Add delivery_partner_id to Subscription

Revision ID: 5b262b1fbf5f
Revises: a8e9f2b1c3d4
Create Date: 2026-07-29 12:37:58.281747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b262b1fbf5f'
down_revision = 'a8e9f2b1c3d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('delivery_partner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_subscriptions_delivery_partner_id'), 'subscriptions', ['delivery_partner_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'delivery_partners', ['delivery_partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_delivery_partner_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'delivery_partner_id')
    # ### end Alembic commands ###
