"""add_profile_fields_to_user

Revision ID: 61209e92294b
Revises: 45461d86e5a3
Create Date: 2026-06-15 14:44:27.364881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61209e92294b'
down_revision = '45461d86e5a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('delivery_notifications_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('payment_notifications_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('promotional_notifications_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'promotional_notifications_enabled')
    op.drop_column('users', 'payment_notifications_enabled')
    op.drop_column('users', 'delivery_notifications_enabled')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
