"""add_multi_product_subscriptions

Revision ID: 6dec8b9db0d8
Revises: af8c433e2907
Create Date: 2026-06-19 07:24:42.204780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dec8b9db0d8'
down_revision = 'af8c433e2907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_items',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_delivery', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_items_id'), 'subscription_items', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_items_product_id'), 'subscription_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_subscription_items_subscription_id'), 'subscription_items', ['subscription_id'], unique=False)
    op.create_table('subscription_pause_history',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pause_reason', sa.String(length=500), nullable=True),
    sa.Column('paused_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_pause_history_id'), 'subscription_pause_history', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_pause_history_subscription_id'), 'subscription_pause_history', ['subscription_id'], unique=False)
    op.create_table('subscription_status_history',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_status_history_id'), 'subscription_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_status_history_subscription_id'), 'subscription_status_history', ['subscription_id'], unique=False)
    op.create_table('subscription_delivery_history',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_id'], ['subscription_deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_delivery_history_delivery_id'), 'subscription_delivery_history', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_subscription_delivery_history_id'), 'subscription_delivery_history', ['id'], unique=False)
    op.create_table('subscription_payment_history',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_payment_history_id'), 'subscription_payment_history', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_payment_history_payment_id'), 'subscription_payment_history', ['payment_id'], unique=False)
    op.create_index(op.f('ix_subscription_payment_history_subscription_id'), 'subscription_payment_history', ['subscription_id'], unique=False)
    op.alter_column('subscriptions', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # Data migration: copy existing subscriptions to subscription_items
    op.execute(
        "INSERT INTO subscription_items (id, subscription_id, product_id, quantity, price_per_delivery, created_at, updated_at) "
        "SELECT gen_random_uuid(), id, product_id, 1, price_per_delivery, created_at, updated_at "
        "FROM subscriptions WHERE product_id IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_subscription_payment_history_subscription_id'), table_name='subscription_payment_history')
    op.drop_index(op.f('ix_subscription_payment_history_payment_id'), table_name='subscription_payment_history')
    op.drop_index(op.f('ix_subscription_payment_history_id'), table_name='subscription_payment_history')
    op.drop_table('subscription_payment_history')
    op.drop_index(op.f('ix_subscription_delivery_history_id'), table_name='subscription_delivery_history')
    op.drop_index(op.f('ix_subscription_delivery_history_delivery_id'), table_name='subscription_delivery_history')
    op.drop_table('subscription_delivery_history')
    op.drop_index(op.f('ix_subscription_status_history_subscription_id'), table_name='subscription_status_history')
    op.drop_index(op.f('ix_subscription_status_history_id'), table_name='subscription_status_history')
    op.drop_table('subscription_status_history')
    op.drop_index(op.f('ix_subscription_pause_history_subscription_id'), table_name='subscription_pause_history')
    op.drop_index(op.f('ix_subscription_pause_history_id'), table_name='subscription_pause_history')
    op.drop_table('subscription_pause_history')
    op.drop_index(op.f('ix_subscription_items_subscription_id'), table_name='subscription_items')
    op.drop_index(op.f('ix_subscription_items_product_id'), table_name='subscription_items')
    op.drop_index(op.f('ix_subscription_items_id'), table_name='subscription_items')
    op.drop_table('subscription_items')
    # ### end Alembic commands ###
