"""add_package_cart

Revision ID: 9bd56e75b765
Revises: 377898d26092
Create Date: 2026-07-02 14:17:50.030354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd56e75b765'
down_revision = '377898d26092'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_carts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_package_cart_qty_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_package_cart_customer_product')
    )
    op.create_index(op.f('ix_package_carts_customer_id'), 'package_carts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_package_carts_id'), 'package_carts', ['id'], unique=False)
    op.create_index(op.f('ix_package_carts_product_id'), 'package_carts', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_carts_product_id'), table_name='package_carts')
    op.drop_index(op.f('ix_package_carts_id'), table_name='package_carts')
    op.drop_index(op.f('ix_package_carts_customer_id'), table_name='package_carts')
    op.drop_table('package_carts')
    # ### end Alembic commands ###
