"""update_product_schema

Revision ID: af8c433e2907
Revises: 3b195ec730cf
Create Date: 2026-06-17 06:36:47.596620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8c433e2907'
down_revision = '3b195ec730cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    product_status = sa.Enum('draft', 'published', 'hidden', name='product_status_enum')
    product_status.create(op.get_bind(), checkfirst=True)
    product_availability = sa.Enum('available', 'out_of_stock', 'temporarily_unavailable', name='product_availability_enum')
    product_availability.create(op.get_bind(), checkfirst=True)

    op.add_column('products', sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('products', sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('status', product_status, server_default='draft', nullable=False))
    op.add_column('products', sa.Column('availability', product_availability, server_default='available', nullable=False))
    op.add_column('products', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('is_popular', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('is_today_special', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.drop_column('products', 'unit')
    op.drop_column('products', 'sort_order')
    op.drop_column('products', 'is_available')
    op.drop_column('products', 'price_per_unit')
    op.drop_column('products', 'mrp')
    op.drop_column('products', 'unit_size')
    op.drop_column('products', 'short_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('unit_size', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('mrp', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('price_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_column('products', 'is_today_special')
    op.drop_column('products', 'is_popular')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'display_order')
    op.drop_column('products', 'availability')
    op.drop_column('products', 'status')
    op.drop_column('products', 'discount_price')
    op.drop_column('products', 'price')
    product_status = sa.Enum('draft', 'published', 'hidden', name='product_status_enum')
    product_status.drop(op.get_bind(), checkfirst=True)
    product_availability = sa.Enum('available', 'out_of_stock', 'temporarily_unavailable', name='product_availability_enum')
    product_availability.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
