"""add_fruit_ordering_tables

Revision ID: b7dceb64d029
Revises: af8c433e2907
Create Date: 2026-06-21 11:52:49.376635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dceb64d029'
down_revision = 'af8c433e2907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruits',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('availability_status', sa.Enum('in_stock', 'out_of_stock', 'temporarily_unavailable', name='fruit_availability_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_per_kg > 0', name='ck_fruits_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruits_availability_status'), 'fruits', ['availability_status'], unique=False)
    op.create_index(op.f('ix_fruits_id'), 'fruits', ['id'], unique=False)
    op.create_index(op.f('ix_fruits_is_active'), 'fruits', ['is_active'], unique=False)
    op.create_index(op.f('ix_fruits_name'), 'fruits', ['name'], unique=False)
    op.create_table('fruit_carts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('fruit_id', sa.UUID(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_kg > 0', name='ck_fruit_cart_qty_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fruit_id'], ['fruits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'fruit_id', name='uq_fruit_cart_customer_fruit')
    )
    op.create_index(op.f('ix_fruit_carts_customer_id'), 'fruit_carts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fruit_carts_fruit_id'), 'fruit_carts', ['fruit_id'], unique=False)
    op.create_index(op.f('ix_fruit_carts_id'), 'fruit_carts', ['id'], unique=False)
    op.create_table('fruit_orders',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'initiated', 'success', 'failed', name='fruit_payment_status_enum'), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_signature', sa.String(length=500), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_status', sa.Enum('pending', 'preparing', 'ready', 'out_for_delivery', 'delivered', 'cancelled', name='fruit_order_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_orders_customer_id'), 'fruit_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fruit_orders_gateway_order_id'), 'fruit_orders', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_fruit_orders_gateway_payment_id'), 'fruit_orders', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_fruit_orders_id'), 'fruit_orders', ['id'], unique=False)
    op.create_index(op.f('ix_fruit_orders_order_number'), 'fruit_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_fruit_orders_order_status'), 'fruit_orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_fruit_orders_payment_status'), 'fruit_orders', ['payment_status'], unique=False)
    op.create_table('fruit_order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('fruit_id', sa.UUID(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_per_kg > 0', name='ck_fruit_order_item_price_positive'),
    sa.CheckConstraint('quantity_kg > 0', name='ck_fruit_order_item_qty_positive'),
    sa.ForeignKeyConstraint(['fruit_id'], ['fruits.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['fruit_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_order_items_fruit_id'), 'fruit_order_items', ['fruit_id'], unique=False)
    op.create_index(op.f('ix_fruit_order_items_id'), 'fruit_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_fruit_order_items_order_id'), 'fruit_order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fruit_order_items_order_id'), table_name='fruit_order_items')
    op.drop_index(op.f('ix_fruit_order_items_id'), table_name='fruit_order_items')
    op.drop_index(op.f('ix_fruit_order_items_fruit_id'), table_name='fruit_order_items')
    op.drop_table('fruit_order_items')
    op.drop_index(op.f('ix_fruit_orders_payment_status'), table_name='fruit_orders')
    op.drop_index(op.f('ix_fruit_orders_order_status'), table_name='fruit_orders')
    op.drop_index(op.f('ix_fruit_orders_order_number'), table_name='fruit_orders')
    op.drop_index(op.f('ix_fruit_orders_id'), table_name='fruit_orders')
    op.drop_index(op.f('ix_fruit_orders_gateway_payment_id'), table_name='fruit_orders')
    op.drop_index(op.f('ix_fruit_orders_gateway_order_id'), table_name='fruit_orders')
    op.drop_index(op.f('ix_fruit_orders_customer_id'), table_name='fruit_orders')
    op.drop_table('fruit_orders')
    op.drop_index(op.f('ix_fruit_carts_id'), table_name='fruit_carts')
    op.drop_index(op.f('ix_fruit_carts_fruit_id'), table_name='fruit_carts')
    op.drop_index(op.f('ix_fruit_carts_customer_id'), table_name='fruit_carts')
    op.drop_table('fruit_carts')
    op.drop_index(op.f('ix_fruits_name'), table_name='fruits')
    op.drop_index(op.f('ix_fruits_is_active'), table_name='fruits')
    op.drop_index(op.f('ix_fruits_id'), table_name='fruits')
    op.drop_index(op.f('ix_fruits_availability_status'), table_name='fruits')
    op.drop_table('fruits')
    # ### end Alembic commands ###
