"""Sync missing schema

Revision ID: bdf89e07b9a2
Revises: 49e6beddf127
Create Date: 2026-06-27 21:35:39.474231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf89e07b9a2'
down_revision = '49e6beddf127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'category_name')
    # ### end Alembic commands ###
