"""add_fcm_columns_and_notification_history

Revision ID: e17a8f588fe8
Revises: 50ccac5a569e
Create Date: 2026-07-04 07:58:43.563446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17a8f588fe8'
down_revision = '50ccac5a569e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_history_id'), 'notification_history', ['id'], unique=False)
    op.create_index(op.f('ix_notification_history_notification_type'), 'notification_history', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_history_user_id'), 'notification_history', ['user_id'], unique=False)
    op.add_column('admin_settings', sa.Column('delivery_charge_0_to_5_km', sa.Numeric(precision=8, scale=2), server_default='0.0', nullable=False))
    op.add_column('admin_settings', sa.Column('delivery_charge_5_to_10_km', sa.Numeric(precision=8, scale=2), server_default='15.0', nullable=False))
    op.add_column('admin_settings', sa.Column('delivery_charge_10_to_15_km', sa.Numeric(precision=8, scale=2), server_default='25.0', nullable=False))
    op.add_column('admin_settings', sa.Column('max_delivery_distance_km', sa.Numeric(precision=5, scale=2), server_default='15.0', nullable=False))
    op.add_column('admin_settings', sa.Column('delivery_boy_reminder_time', sa.Time(), nullable=True))
    op.create_unique_constraint('uq_package_cart_customer_product', 'package_carts', ['customer_id', 'product_id'])
    op.add_column('users', sa.Column('device_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_token_update', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('notification_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_enabled')
    op.drop_column('users', 'last_token_update')
    op.drop_column('users', 'device_type')
    op.drop_constraint('uq_package_cart_customer_product', 'package_carts', type_='unique')
    op.drop_column('admin_settings', 'delivery_boy_reminder_time')
    op.drop_column('admin_settings', 'max_delivery_distance_km')
    op.drop_column('admin_settings', 'delivery_charge_10_to_15_km')
    op.drop_column('admin_settings', 'delivery_charge_5_to_10_km')
    op.drop_column('admin_settings', 'delivery_charge_0_to_5_km')
    op.drop_index(op.f('ix_notification_history_user_id'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_notification_type'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_id'), table_name='notification_history')
    op.drop_table('notification_history')
    # ### end Alembic commands ###
